export { default as LoginPage } from './LoginPage'
export { default as AdvertsPage } from './AdvertsPage'
export { default as AdvertPage } from './AdvertPage'
export { default as NewAdvertPage } from './NewAdvertPage'
export { default as NotFoundPage } from './NotFoundPage'
